// <auto-generated />
using FindAFish.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FindAFish.Migrations
{
    [DbContext(typeof(FindaFishDbContext))]
    partial class FindaFishDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FindAFish.Models.FishGenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genus");

                    b.HasKey("Id");

                    b.ToTable("FishGenus");
                });

            modelBuilder.Entity("FindAFish.Models.FishSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GenusId");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.ToTable("FishSpecies");
                });

            modelBuilder.Entity("FindAFish.Models.FishSpecies", b =>
                {
                    b.HasOne("FindAFish.Models.FishGenus", "Genus")
                        .WithMany("FishSpecies")
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
